Category.find_or_create_by(category:"life")
Category.find_or_create_by(category:"work")
Category.find_or_create_by(category:"hobby")
Category.find_or_create_by(category:"other")
Category.find_or_create_by(category:"programming")
